#SPDX-License-Identifier: MIT-0
---
- name: Download Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
    mode: '0644'

- name: Install Vector
  ansible.builtin.yum:
    name:
      - "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"

- name: Create systemd unit file for Vector
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: '0644'

- name: Enable and start Vector service
  ansible.builtin.systemd:
    name: vector
    enabled: true
    state: started

- name: Deploy Vector configuration
  ansible.builtin.template:
    src: "{{ vector_template_src }}"
    dest: "{{ vector_config_file }}"
    mode: '0644'
  notify: Restart Vector
